In [780]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [781]:
import numpy as np

In [782]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

Matrix/ 2D Array

In [783]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [784]:
a[2:5]

array([3, 4, 5])

In [785]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [786]:
a[3:]

array([4, 5, 6, 7])

In [787]:
a[-2]

6

In [788]:
a[2:-3]

array([3, 4])

In [789]:
a[-5:]

array([3, 4, 5, 6, 7])

In [790]:
a[-5:-1]

array([3, 4, 5, 6])

In [791]:
a[-1:2]

array([], dtype=int64)

In [792]:
np.size(a)

7

In [793]:
a[a[2]]

4

In [794]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [795]:
a[2:5]

array([3, 4, 5])

In [796]:
a[a[3:5]]

array([5, 6])

In [797]:
sorted(a, reverse = True)

[7, 6, 5, 4, 3, 2, 1]

In [798]:
np.shape(a)

(7,)

In [799]:
a = a.reshape(1,7)
np.shape(a)

(1, 7)

In [800]:
a

array([[1, 2, 3, 4, 5, 6, 7]])

In [801]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [802]:
b[0,0]

1

In [803]:
b[:,1]

array([2, 5, 8])

In [804]:
b[:,-1]

array([3, 6, 9])

In [805]:
b[0:2,:] = 8
b

array([[8, 8, 8],
       [8, 8, 8],
       [7, 8, 9]])

In [806]:
b.shape

(3, 3)

In [807]:
np.size(b,1)

3

In [808]:
np.ndim(b)

2

In [809]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [810]:
a = np.array(np_mix_matrix[:,1], dtype = int)
a

array([2, 4, 6])

In [811]:
a = np.zeros((5,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [812]:
a = np.ones((5,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [813]:
a = np.full((5,5),8)
a

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [814]:
b = np.eye(5,5)
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [815]:
a*b

array([[8., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0.],
       [0., 0., 8., 0., 0.],
       [0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 8.]])

In [816]:
np.matmul(a,b)

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

In [817]:
np.sqrt(np.ones((5,5))*9)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [818]:
np.empty((6*6))

array([1.        , 1.        , 0.8       , 1.        , 1.        ,
       0.92941176, 0.62745098, 1.        , 0.99607843, 0.85098039,
       0.4627451 , 1.        , 0.99607843, 0.69803922, 0.29803922,
       1.        , 0.99215686, 0.55294118, 0.23529412, 1.        ,
       0.98823529, 0.30588235, 0.16470588, 1.        , 0.89019608,
       0.10196078, 0.10980392, 1.        , 0.74117647, 0.        ,
       0.14901961, 1.        , 0.50196078, 0.        , 0.14901961,
       1.        ])

In [819]:
np.random.rand(5,5)

array([[0.47459353, 0.65588596, 0.60606166, 0.4991258 , 0.74390124],
       [0.12845469, 0.80658373, 0.52173278, 0.93378981, 0.34028692],
       [0.19271708, 0.91396057, 0.40258499, 0.47017882, 0.44453136],
       [0.58612437, 0.60730513, 0.94798254, 0.40822304, 0.1263573 ],
       [0.66719614, 0.88101232, 0.6194462 , 0.06841825, 0.30952459]])

In [820]:
#ex1
#ข้ามๆๆ

In [821]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5,replace=False)

array([ 2,  1,  7, 10,  3])

In [822]:
np_matrix = np.round(np.random.rand(5,5))
np_matrix

array([[1., 0., 1., 1., 1.],
       [0., 1., 1., 0., 1.],
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 1., 1.]])

In [823]:
idx_choose = np.random.choice(5,3, replace=False)
idx_choose

array([4, 3, 0])

In [824]:
np_matrix = np.round(np.random.rand(1000,5))
np_matrix

array([[1., 0., 1., 0., 0.],
       [0., 0., 1., 1., 1.],
       [0., 1., 0., 0., 1.],
       ...,
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [825]:
idx_choose = np.random.choice(1000,100, replace=False)
idx_choose

array([ 99, 659, 544, 683,  65, 939,  31, 646, 739, 374, 847, 195, 363,
       701, 177, 522,  10, 693, 547, 594, 887,  40,  43, 839, 345, 751,
       331, 775, 901, 139, 624, 992, 994, 733, 535, 314, 379,  75,  86,
       912, 454, 398, 441, 437, 230, 735, 521, 788, 622, 615, 663, 289,
       212, 581, 147, 690, 981, 127, 183, 490, 305, 213, 941, 128, 589,
       455, 975, 229,  29, 792, 630, 859, 420, 656,  37, 140, 961, 440,
       518, 381, 328, 904, 824, 386, 579, 511, 347, 799, 137, 688, 877,
       706, 776, 746, 873, 958, 853, 299, 804, 546])

In [826]:
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[0., 1., 1., 1., 1.],
       [0., 0., 1., 0., 1.],
       [1., 0., 1., 1., 1.],
       [1., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 1., 1., 1.],
       [1., 0., 0., 1., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0.],
       [1., 0., 1., 1., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 0., 1., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 1., 0., 1.],
       [1., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 1.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 1.],
       [1., 1., 0., 1., 1.],
       [0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 1.],
       [1., 0., 1., 0., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 1., 0., 1.],
       [1., 1.

In [827]:
#ex2
np_matrix = np.random.rand(10,5)
np_matrix

array([[0.78764035, 0.51866685, 0.40611345, 0.3465756 , 0.46795828],
       [0.10197544, 0.10785116, 0.63083401, 0.25018783, 0.34316331],
       [0.90050345, 0.12628867, 0.40464406, 0.95538917, 0.80417202],
       [0.31724908, 0.9778942 , 0.43660151, 0.39458476, 0.46304529],
       [0.69395104, 0.72896164, 0.88065316, 0.15188046, 0.37705457],
       [0.53870621, 0.37774992, 0.23426941, 0.14466   , 0.07055741],
       [0.04981671, 0.25630252, 0.63494272, 0.00652992, 0.16518902],
       [0.21254499, 0.99055561, 0.834726  , 0.65497087, 0.60199748],
       [0.83920005, 0.31331811, 0.28842979, 0.72859524, 0.44152797],
       [0.66010653, 0.14901975, 0.69398552, 0.14449563, 0.20844594]])

In [828]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[2, 0, 1, 0, 2],
       [2, 2, 0, 0, 2],
       [1, 2, 2, 0, 2],
       [1, 0, 2, 2, 0],
       [0, 2, 2, 2, 2]])

In [829]:
i,j = np.where(np_matrix == 2)
[(i[ii],j[ii]) for ii in range(len(j))]

[(0, 0),
 (0, 4),
 (1, 0),
 (1, 1),
 (1, 4),
 (2, 1),
 (2, 2),
 (2, 4),
 (3, 2),
 (3, 3),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 4)]

In [830]:
rng = np.random.RandomState(0)

In [831]:
rng = np.random.RandomState(0)
[np.round(rng.rand()*10) for item in range(10)]

[5.0, 7.0, 6.0, 5.0, 4.0, 6.0, 4.0, 9.0, 10.0, 4.0]

In [832]:
rng = np.random.RandomState(5)
np_matrix = rng.randint(3,size = (5,1))
np_matrix

array([[2],
       [1],
       [2],
       [2],
       [0]])

In [833]:
a = np_matrix == (1)
a

array([[False],
       [ True],
       [False],
       [False],
       [False]])

In [834]:
np_matrix[a] = 99
np_matrix

array([[ 2],
       [99],
       [ 2],
       [ 2],
       [ 0]])

In [835]:
#rng = np.random.default_rng()

^ เรียกใข้คำสั่งของ numpy rng (ครั้งเดียว)

In [836]:
#ex2
rng = np.random.default_rng()
np_matrix = rng.random((10, 5))
np_matrix[:,-1] = rng.integers(2, size=10)
np_matrix

array([[0.77913394, 0.09302839, 0.70492398, 0.35744426, 1.        ],
       [0.99683327, 0.55014066, 0.10286895, 0.17267199, 1.        ],
       [0.41788829, 0.34797987, 0.43629622, 0.30002628, 0.        ],
       [0.22782362, 0.35820542, 0.61022275, 0.36565208, 1.        ],
       [0.34352253, 0.86874433, 0.54616027, 0.94826358, 1.        ],
       [0.01768008, 0.15385854, 0.06071649, 0.07325629, 1.        ],
       [0.85301458, 0.71394754, 0.55294648, 0.56250271, 1.        ],
       [0.55844676, 0.25005304, 0.25251515, 0.54085964, 0.        ],
       [0.06830527, 0.32185086, 0.85944402, 0.78453283, 0.        ],
       [0.06797645, 0.14116686, 0.51871321, 0.73989088, 0.        ]])

In [837]:
rng = np.random.default_rng()
rng.integers(2, size=10)

array([1, 0, 0, 1, 0, 1, 0, 1, 1, 1])

In [838]:
np_matrix = np.random.randint(5,size = (5,5))
np_matrix

array([[2, 1, 4, 0, 2],
       [2, 4, 4, 2, 2],
       [1, 0, 3, 4, 1],
       [3, 2, 4, 2, 1],
       [1, 4, 1, 1, 3]])

In [839]:
#ex3
idx = [1,2,3,4,5]
np_matrix[idx.remove(5)]

array([[[2, 1, 4, 0, 2],
        [2, 4, 4, 2, 2],
        [1, 0, 3, 4, 1],
        [3, 2, 4, 2, 1],
        [1, 4, 1, 1, 3]]])

In [846]:
#ex4
rng = np.random.default_rng()
data_matrix = rng.integers(10, size=(10,5))
label_vector = np.random.randint(2,size = 10)
train_data = data_matrix[np.where(label_vector == 0)]
test_data = data_matrix[np.where(label_vector == 1)]
print ("data_matrix" + "\n" + str(data_matrix) + "\n" + "\n" 
       + "label_vector" + "\n" + str(label_vector) + "\n" + "\n"
       + "train_data" + "\n" + str(train_data) + "\n" + "\n"
       + "test_data" + "\n" + str(test_data) + "\n")

data_matrix
[[5 3 8 3 9]
 [7 4 8 5 6]
 [0 3 5 8 9]
 [9 3 7 5 5]
 [9 7 5 5 7]
 [1 1 6 0 3]
 [6 1 5 0 7]
 [8 3 0 9 1]
 [0 2 6 7 3]
 [3 2 4 0 9]]

label_vector
[0 0 0 0 0 1 1 0 1 1]

train_data
[[5 3 8 3 9]
 [7 4 8 5 6]
 [0 3 5 8 9]
 [9 3 7 5 5]
 [9 7 5 5 7]
 [8 3 0 9 1]]

test_data
[[1 1 6 0 3]
 [6 1 5 0 7]
 [0 2 6 7 3]
 [3 2 4 0 9]]

